import {introduction,paperLessons,teach} from './teaching.js?v=expanded-space-2';
import {sourceInfo,sourceLesson,lessons} from './data.js?v=expanded-space-2';
import {D,DK,EPS,VOCAB} from './model.js?v=expanded-space-2';
export const format=(x,n=4)=>x===-Infinity?'−∞':x===Infinity?'∞':Number.isFinite(x)?(Math.abs(x)<.5*10**(-n)?0:x).toFixed(n):'—';
export function scopeName(t){const head=t.head===undefined?'':` · head ${t.head+1}`;return t.scope?.startsWith('enc.')?`Encoder ${+t.scope.split('.')[1]+1}${head}`:t.scope?.startsWith('dec.')?`Decoder ${+t.scope.split('.')[1]+1}${t.cross?' · cross-attention':''}${head}`:t.scope==='source'?'Source sequence':t.scope==='target'?'Shifted target':t.scope==='training'?'Learning from the example':'Next-token prediction';}
export function tensorName(id){return id.startsWith('@')?id.slice(1).replace(/enc\.(\d+)/,(_,n)=>`Encoder ${+n+1}`).replace(/dec\.(\d+)/,(_,n)=>`Decoder ${+n+1}`).replace(/\.h(\d+)/,(_,n)=>` · head ${+n+1}`).replaceAll('.',' · '):id;}
export const conceptLabels={attention:'Why attention',tokens:'Tokenization',embeddings:'Embeddings',position:'Position',qkv:'Q, K and V',scores:'Dot products',softmax:'Softmax',values:'Mixing values',context:'Context',heads:'Multiple heads',mask:'Masking',norm:'Residuals & normalization',ffn:'Feed-forward',architecture:'The whole architecture',generation:'Prediction',training:'Learning',walkthrough:'The complete journey'};
export function explanation(t,m){const ins=t.inputs.map(id=>m.tensors.get(id)),s=t.shape.join(' × '),base={
 backward:`Read the computation in reverse. For the selected coordinate, multiply each consumer’s loss gradient by that consumer’s local derivative, then sum every contribution. These are the exact scalar operations from the current forward pass. Select another coordinate to trace its chain rule.`,
 tokens:`This example uses a small word-level vocabulary. Each token selects a vocabulary index; an ID is a lookup address, not a measure of meaning. Real language models commonly use subword tokens.`,
 lookup:`Each token selects a learned row from the embedding table. These ${s} values begin the numerical journey. Change an embedding coordinate and every downstream calculation is recomputed.`,
 position:`For dimension 2i use sin(position / 10000^(2i/4)); for 2i+1 use cosine. Different frequencies give each position a different four-coordinate signature.`,
 matmul:`Every output cell is a dot product: multiply one input row by one weight column, then add ${ins[0]?.shape[1]||D} products. Select a cube to inspect its exact operands.`,
 add:`Add matching coordinates. A residual route keeps the previous representation while a sublayer contributes an update; the shape stays ${s}.`,
 sub:`Subtract the scaled gradient from the current parameter. This is a preview of the next SGD update; “Train one step” applies it to every active learned parameter.`,
 bias:`The same learned bias vector is added independently at every token position. Select an output cell to see the input coordinate and its bias.`,
 scale:`Divide every coordinate by ${format(t.divisor)}. The source values change, while the tensor shape remains ${s}.`,
 transpose:`Exchange row and column indices. K[i,j] becomes Kᵀ[j,i], so a query row can be compared with a key column. No value is learned or changed here.`,
 mask:t.causal?`A query may use its current position and earlier positions. Future and padding keys receive −∞, which becomes zero after exponentiation.`:`Padding keys receive −∞ before softmax. Other positions remain visible; encoder and cross-attention can use the whole unpadded source.`,
 rowmax:`Find the largest allowed score in each row. Subtracting it before exponentiation prevents overflow without changing the final softmax probabilities.`,
 rowSubtract:t.normalization?`Subtract this token’s mean from all four features. Normalization happens across features within a token, independently for each position.`:`Subtract the same maximum from each score in a row. Relative differences stay the same; the largest shifted score is zero.`,
 exp:`Exponentiate every shifted score. Finite values become positive, and exp(−∞) is exactly zero for masked positions.`,
 rowSum:`Sum all exponentials in each row. This denominator turns the individual exponentials into relative probabilities.`,
 rowDivide:t.normalization?`Divide each centered feature by √(variance + ε). The tiny ε = ${EPS} keeps division stable, even when a row has little variation.`:`Divide each exponential by its row sum. Every row now sums to one. These are computed probabilities, and they change when you edit any upstream value.`,
 concat:`The heads have separate learned projections. Join their two-coordinate outputs side by side: 2 heads × 2 features = 4 features. They occupy independent depth layers in this scene.`,
 rowMean:`Average the four feature coordinates for each token. Every row has its own statistic; other tokens are not included in that row’s normalization.`,
 square:`Square each centered coordinate. These nonnegative differences measure the spread of a token’s features.`,
 std:`Add ε = ${EPS} to the variance, then take its square root. This is the denominator used to standardize the row.`,
 affine:`Multiply standardized features by learned γ, then add learned β. Normalization need not force the final mean to zero or variance to one after this learned transformation.`,
 relu:`Apply max(0, x) to every expanded feature. Negative activations become zero; positive activations remain unchanged. This nonlinearity lets the feed-forward network do more than one linear map.`,
 gather:`Select the probability assigned to each known next-token target. Teacher forcing uses a shifted target input, with a causal mask preventing the decoder from reading its answer.`,
 neglog:`The loss for a correct target is −log p(target), in nats. Confident correct predictions have a small loss; low probability on the correct target has a larger loss.`,
 mean:`Average the target losses for this example. This scalar is differentiated through the entire encoder–decoder computation.`,
 gradient:`A shared query weight contributes at several positions. Multiply each incoming loss gradient by the local derivative, then sum the contributions. The products below are taken from the actual reverse-mode computation.`,
 multiplyScalar:`Multiply the gradient by the learning rate ${format(m.config.learningRate)}. The update changes learned parameters; activations are recalculated on the next forward pass.`
 }[t.op]||'Inspect the live values and follow their dependencies through the model.';
 if(t.id==='source.input'||t.id==='target.input')return 'Add each positional coordinate to the matching scaled embedding coordinate. Both have four features, so the sum retains the shape required by attention. The same token at a different position now receives a different input representation.';
 if(t.id.endsWith('.scaled')&&(t.scope==='source'||t.scope==='target'))return `Multiply every embedding coordinate by √d_model = √4 = 2, as in the original architecture. The initial values are small and editable so you can follow the arithmetic.`;
 if(t.id.endsWith('.Q'))return(t.cross?'These queries come from the decoder’s current state. ':'Each token gets its own query. ')+base;
 if(t.id.endsWith('.K')||t.id.endsWith('.V'))return(t.cross?'Cross-attention uses the final encoder memory here. ':'The same learned projection is applied at every position. ')+base;
 if(t.id.endsWith('.scores'))return `A query compares with every key. Each score adds ${DK} coordinate products; it can be positive or negative and is not yet a probability.`;
 if(t.id.endsWith('.Z'))return `Each output feature sums attention-weighted value features from the visible positions. The moving contributions are tied to the selected output coordinate’s real operands.`;
 if(t.id==='learn.clipped')return `The current global gradient norm is ${format(m.gradientNorm)}. The clipping limit is 5, so every gradient is multiplied by ${format(m.clipScale)} before the learning-rate step.`;
 if(t.id==='output.A')return `Each row is a distribution over ${VOCAB.length} vocabulary items. In generation, use the last row. This small model starts with seeded, untrained weights; learning can improve this one example.`;
 return base;
}
const referenceBindings={
  1:'source.ids',2:'source.lookup',3:'source.lookup',4:'source.lookup',5:'source.lookup',6:'enc.0.self.output',7:'source.lookup',8:'source.lookup',9:'enc.0.self.output',10:'output.A',11:'enc.0.self.h0.Z',12:'enc.0.self.output',13:'enc.0.self.h0.Q',14:'enc.0.self.h0.Q',15:'enc.0.self.h0.Q',16:'enc.0.self.h1.Q',17:'enc.0.self.h0.scores',18:'enc.0.self.h0.scores',19:'enc.0.self.h0.scores',20:'enc.0.self.h0.A',21:'enc.0.self.h0.scaled',22:'enc.0.self.h0.A',23:'target.ids',24:'output.A',25:'dec.0.self.h0.masked',26:'enc.0.self.h0.V',27:'enc.0.self.h0.V',28:'enc.0.self.h1.V',29:'enc.0.self.h0.Z',30:'enc.0.self.h0.Q',31:'enc.0.self.output',32:'enc.0.self.output',33:'enc.0.self.concat',34:'enc.0.self.concat',35:'source.ids',36:'enc.0.self.h0.A',37:'enc.0.self.h0.A',38:'enc.0.self.h0.A',39:'enc.0.self.h0.A',40:'enc.0.self.h0.A',41:'world',42:'enc.0.self.h0.Q',43:'source.lookup',44:'source.input',45:'enc.0.self.h0.Q',46:'enc.0.self.h0.Q',47:'enc.0.self.h0.Q',48:'enc.0.self.h0.scores',49:'enc.0.self.h0.scaled',50:'enc.0.self.h0.A',51:'enc.0.self.h0.A',52:'enc.0.self.h0.Z',53:'enc.0.self.h0.Z',54:'enc.0.self.h0.A',55:'enc.0.self.h0.A',56:'enc.0.self.h0.Q',57:'enc.0.self.h0.scaled',58:'enc.0.self.h0.A',59:'enc.0.self.h0.Z',60:'dec.0.cross.h0.A',61:'enc.0.self.concat',62:'enc.0.self.norm.output',63:'world',64:'enc.0.ff.relu',65:'world',66:'source.input',67:'source.input',68:'enc.0.ff.bias',69:'world',70:'source.input'
};
export function numberCourse(entries){let cursor=0;entries.forEach((s,i)=>{s.index=i;s.start=cursor;cursor+=s.length;});entries.total=cursor;return entries;}
export function ensureScene(course,id){let index=course.findIndex(s=>s.id===id);if(index>=0)return index;const entry=course.archive.find(s=>s.id===id);if(!entry)return -1;course.splice(course.length-1,0,{...entry});numberCourse(course);return course.length-2;}
export function buildCourse(model){
 const live=model.trace.map(t=>({id:t.id,tensor:t.id,title:t.label,body:explanation(t,model),...teach(t,model,explanation(t,model)),concept:t.concept,group:scopeName(t),length:t.micro?1.15:1.5}));
 const ids=['source.ids','source.lookup','source.scaled','source.position','source.input',
 'enc.0.self.h0.Q','enc.0.self.h0.K','enc.0.self.h0.V','enc.0.self.h0.KT','enc.0.self.h0.scores','enc.0.self.h0.scaled','enc.0.self.h0.masked','enc.0.self.h0.max','enc.0.self.h0.shift','enc.0.self.h0.exp','enc.0.self.h0.sum','enc.0.self.h0.A','enc.0.self.h0.Z','enc.0.self.h1.Q','enc.0.self.h1.A','enc.0.self.h1.Z','enc.0.self.concat','enc.0.self.output','enc.0.self.residual',
 'enc.0.self.norm.mean','enc.0.self.norm.center','enc.0.self.norm.squared','enc.0.self.norm.variance','enc.0.self.norm.std','enc.0.self.norm.unit','enc.0.self.norm.output',
 'enc.0.ff.expand','enc.0.ff.biased','enc.0.ff.relu','enc.0.ff.contract','enc.0.ff.bias','enc.0.ff.residual','enc.0.ff.norm.output','enc.1.ff.norm.output',
 'target.ids','target.lookup','target.scaled','target.position','target.input','dec.0.self.h0.Q','dec.0.self.h0.scores','dec.0.self.h0.masked','dec.0.self.h0.A','dec.0.self.h0.Z','dec.0.self.concat','dec.0.self.output','dec.0.self.residual','dec.0.self.norm.output',
 'dec.0.cross.h0.Q','dec.0.cross.h0.K','dec.0.cross.h0.V','dec.0.cross.h0.scores','dec.0.cross.h0.A','dec.0.cross.h0.Z','dec.0.cross.concat','dec.0.cross.output','dec.0.cross.residual','dec.0.cross.norm.output','dec.0.ff.expand','dec.0.ff.relu','dec.0.ff.contract','dec.0.ff.residual','dec.0.ff.norm.output','dec.1.ff.norm.output',
 'output.project','output.logits','output.temperature','output.max','output.shift','output.exp','output.sum','output.A','loss.targets','loss.tokens','loss.mean','backward.loss.mean','backward.output.logits','backward.dec.0.cross.h0.Q','backward.enc.0.self.h0.Q','backward.@source.embedding','learn.gradient','learn.clipped','learn.delta','learn.next'];
 const entries=[...introduction.map(s=>({...s})),...live.filter(s=>!s.id.startsWith('backward.')&&!s.id.startsWith('learn.')),...ids.filter(id=>id.startsWith('backward.')||id.startsWith('learn.')).map(id=>live.find(t=>t.id===id)).filter(Boolean)];
 const sample=entries.find(s=>s.id==='known-example'),ex=model.customExample||{source:model.sourceTokens,target:model.targets};
 Object.assign(sample,{title:'Follow your text through one complete computation.',why:'The source is “'+ex.source.join(' ')+'”. The expected output is “'+ex.target.filter(t=>t!=='<eos>').join(' ')+'”. This miniature starts untrained: a prediction is calculated, not guaranteed correct.',how:'First assign token IDs, look up four learned features, then add position. The encoder exchanges context; the decoder predicts the expected output one token at a time. Open Your text to replace either sequence.',result:'When source and target match, this is a copy task. It is a clear way to study sequence learning without claiming translation knowledge. Every later live tensor uses these same inputs.'});
 sample.body=sample.why;
 const generate={id:'generate',tensor:model.output,title:'Generate one token, then extend the prefix.',why:'At inference the next target is unknown. The decoder must use its own earlier predictions, so a correct teacher-forced prediction does not by itself guarantee a correct generated sequence.',how:'Start with <bos>. Read the last row of the vocabulary distribution, choose its highest-probability token, append it, and evaluate the longer prefix again. The learned weights remain fixed during generation.',result:'Use Experiment to train the example, start generation and append predicted tokens. The process ends at <eos> or the demonstration length limit. Greedy decoding is a simple teaching choice; the paper evaluates beam search.',concept:'generation',group:'AUTOREGRESSIVE GENERATION',length:1.7};generate.body=generate.why;entries.push(generate,...paperLessons.map(s=>({...s})));
 entries.archive=[...live];
 for(let n=1;n<=70;n++){const binding=referenceBindings[n],tensor=model.tensors.has(binding)?binding:binding==='world'?'world':model.encoderOutput;const t=model.tensors.get(tensor),info=sourceInfo[n-1];entries.archive.push({id:`drawing-${n}`,tensor,title:info[0],body:info[1],...(t?teach(t,model,explanation(t,model)):{why:info[1],how:'Follow the original encoder–decoder connections, with source input at the left and a shifted target at the right.',result:'Use the architecture blocks to connect this reference concept to its live numerical calculation.'}),concept:lessons[sourceLesson(n)].id,group:`SUPPLIED REFERENCE ${n} / 70`,reference:n,length:1.5});}
 // Integrate all supplied compositions beside their live operation, in teaching order.
 const references=entries.archive.filter(s=>s.reference);
 const introAnchors={35:'problem-recurrence',36:'problem-context',37:'problem-recurrence',38:'solution-attention',39:'solution-attention',40:'solution-attention',41:'two-stacks',42:'known-example',63:'two-stacks',65:'two-stacks',69:'problem-recurrence'};
 for(const ref of references){ref.length=2.2;ref.visualOnly=[1,4,5,6,7,8,33,35,36,37,38,39,40,41,42,54,55,60,61,69].includes(ref.reference);if(ref.visualOnly){ref.why=ref.body+' This scene isolates the conceptual relationship before the live arithmetic.';ref.how=ref.reference===54||ref.reference===55?'This separate six-token toy example uses explicit two-coordinate query and key vectors. Compute every dot product, divide by √2, exponentiate, and normalize each row. The moving highlight shows the exact query, key, score and weight. These are illustrative inputs, not learned attention from the browser translator.':ref.reference===4||ref.reference===5?'Read the two pairs of embedding vectors. Subtract the man vector from the woman vector to obtain an offset. Translate the same offset to the second pair, then watch the moving endpoint show vector addition. All displayed coordinates are explicit illustrative values.':ref.reference===6||ref.reference===8?'Follow the initial vector and the separate context updates. Each moving endpoint is recomputed by adding a scaled update to the initial coordinates. These illustrative coordinates demonstrate the operation; they are not learned semantic features of the tiny browser model.':ref.reference===33?'Multiply 12,288 model coordinates by 128 head coordinates for each query, key, value, and output slice. Adding the four counts gives 6,291,456 weights in this source example. These are not the dimensions of the original base Transformer or the small browser model.':'Follow the words, connections and highlighted states. The scene keeps the source example and separates its conceptual claim from the numerical browser model. Continue to the following operations to inspect the same mechanism with actual tensors.';ref.result='The relationship is visible at the level of individual words, vectors and operations. A conceptual example explains the mechanism; it does not establish what any particular trained head has learned.';}else ref.why=ref.body+' '+ref.why;}
 const ordered=[];for(const step of entries){ordered.push(step);for(const ref of references){const anchor=introAnchors[ref.reference]||ref.tensor;if(anchor===step.id)ordered.push({...ref});}}
 const placed=new Set(ordered.map(s=>s.id));for(const ref of references)if(!placed.has(ref.id))ordered.splice(ordered.length-1,0,{...ref});
 ordered.archive=entries.archive;
 return numberCourse(ordered);
}
export function locate(course,position){let lo=0,hi=course.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(course[mid].start<=position+1e-9)lo=mid;else hi=mid-1;}const s=course[lo];return{index:lo,local:Math.max(0,Math.min(1,(position-s.start)/s.length))};}
export function hashIndex(course,hash){const value=decodeURIComponent(hash.slice(1));let i=ensureScene(course,value);if(i>=0)return i;const legacy=value.match(/^lesson-(\d+)/);if(legacy){const concept=lessons[Math.max(0,Math.min(16,+legacy[1]-1))].id;return Math.max(0,course.findIndex(s=>s.concept===concept));}return 0;}
export function calculate(model,id,row=0,col=0){
  const t=model.tensors.get(id);if(!t)return null;row=Math.max(0,Math.min(t.shape[0]-1,row));col=Math.max(0,Math.min(t.shape[1]-1,col));
  const ins=t.inputs.map(key=>model.tensors.get(key)),ref=(tensor,r,c)=>({tensor:tensor.id,row:r,col:c,value:tensor.values[r][c]}),a=ins[0],b=ins[1],terms=[];let formula='',result=t.values[row][col];
  const f=x=>format(x,4),at=(tensor,r,c)=>tensor?.values[r]?.[c];
  if(t.op==='backward'||t.op==='gradient'){const chain=model.gradientDetails(t.backwardOf||'@'+t.parameter,row,col);for(const contribution of chain.terms)terms.push({...contribution,label:`${f(contribution.upstream)} × ${f(contribution.derivative)}`});if(chain.seed)terms.unshift({upstream:1,derivative:1,value:1,label:'1 · seed ∂L/∂L',operation:'loss seed'});if(!terms.length)terms.push({upstream:0,derivative:0,value:0,label:'0 · no incoming contribution',operation:'constant'});formula=terms.map(x=>x.label).join(' + ');}
  else if(t.op==='matmul'){for(let k=0;k<a.shape[1];k++)terms.push({a:ref(a,row,k),b:ref(b,k,col),value:at(a,row,k)*at(b,k,col),label:`${f(at(a,row,k))} × ${f(at(b,k,col))}`});formula=terms.map(x=>x.label).join(' + ');}
  else if(['add','sub','bias'].includes(t.op)){const br=t.op==='bias'?0:row;terms.push({a:ref(a,row,col),value:at(a,row,col),label:f(at(a,row,col))},{a:ref(b,br,col),value:at(b,br,col)*(t.op==='sub'?-1:1),label:(t.op==='sub'?'− ':'+ ')+f(at(b,br,col))});formula=`${f(at(a,row,col))} ${t.op==='sub'?'−':'+'} ${f(at(b,br,col))}`;}
  else if(t.op==='scale'){terms.push({a:ref(a,row,col),value:result,label:`${f(at(a,row,col))} ÷ ${f(t.divisor)}`});formula=terms[0].label;}
  else if(t.op==='multiplyScalar'){terms.push({a:ref(a,row,col),value:result,label:`${f(at(a,row,col))} × ${f(t.scalar)}`});formula=terms[0].label;}
  else if(t.op==='rowDivide'||t.op==='rowSubtract'){const av=at(a,row,col),bv=at(b,row,0);terms.push({a:ref(a,row,col),b:ref(b,row,0),value:result,label:`${f(av)} ${t.op==='rowDivide'?'÷':'−'} ${f(bv)}`});formula=terms[0].label;}
  else if(['rowSum','rowMean','mean'].includes(t.op)){const values=t.op==='mean'?a.values.flat():a.values[row];values.forEach((v,j)=>terms.push({a:ref(a,t.op==='mean'?j:row,t.op==='mean'?0:j),value:v/(t.op==='rowSum'?1:values.length),label:f(v)}));formula=`(${values.map(f).join(' + ')})${t.op==='rowSum'?'':` ÷ ${values.length}`}`;}
  else if(t.op==='affine'){const av=at(a,row,col),gamma=at(b,0,col),beta=at(ins[2],0,col);terms.push({a:ref(a,row,col),b:ref(b,0,col),value:av*gamma,label:`${f(av)} × ${f(gamma)}`},{a:ref(ins[2],0,col),value:beta,label:`+ ${f(beta)}`});formula=terms.map(t=>t.label).join(' ');}
  else if(t.op==='lookup'){const sourceRow=t.indices[row];terms.push({a:ref(b,sourceRow,col),value:result,label:`embedding[${sourceRow}, ${col}]`});formula=terms[0].label;}
  else if(t.op==='concat'){let offset=col,which=0;while(offset>=ins[which].shape[1]){offset-=ins[which].shape[1];which++;}terms.push({a:ref(ins[which],row,offset),value:result,label:`head ${which+1}, feature ${offset}`});formula=terms[0].label;}
  else if(t.op==='transpose'){terms.push({a:ref(a,col,row),value:result,label:`K[${col}, ${row}]`});formula=terms[0].label;}
  else if(t.op==='mask'){const allowed=t.allowed[row][col];terms.push({a:ref(a,row,col),value:result,label:allowed?'visible position':'masked position'});formula=allowed?`${f(at(a,row,col))} + 0`:`${f(at(a,row,col))} + (−∞)`;}
  else if(t.op==='position'){const i=Math.floor(col/2),fn=col%2?'cos':'sin';formula=`${fn}(${row} ÷ 10000^(${2*i}/${D}))`;terms.push({value:result,label:formula});}
  else if(t.op==='exp'||t.op==='relu'||t.op==='square'||t.op==='std'||t.op==='neglog'){const v=at(a,row,col);formula=t.op==='exp'?`exp(${f(v)})`:t.op==='relu'?`max(0, ${f(v)})`:t.op==='square'?`${f(v)}²`:t.op==='std'?`√(${f(v)} + ${EPS})`:`−log(${f(v)})`;terms.push({a:ref(a,row,col),value:result,label:formula});}
  else if(t.op==='rowmax'){formula=`max(${a.values[row].map(f).join(', ')})`;a.values[row].forEach((v,j)=>terms.push({a:ref(a,row,j),value:v,label:f(v)}));}
  else if(t.op==='gather'){terms.push({a:ref(a,row,t.targets[row]),value:result,label:`p(${VOCAB[t.targets[row]]})`});formula=terms[0].label;}
  else if(t.op==='tokens'){formula=`vocabulary.indexOf(“${t.tokens[row]}”)`;terms.push({value:result,label:formula});}
  else{formula=t.parameter?'Learned parameter · editable':t.label;terms.push({value:result,label:formula});}
  return {tensor:t,row,col,terms,formula,result,additive:['matmul','add','sub','bias','rowSum','rowMean','mean','affine','backward','gradient'].includes(t.op)};
}
