import {format} from './course.js?v=expanded-space-2';
export const escapeMath=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=(tag,s)=>`<${tag}>${s}</${tag}>`;
export const mi=s=>el('mi',escapeMath(s)),mo=s=>el('mo',escapeMath(s)),mn=s=>s===-Infinity?mo('−')+mo('∞'):s===Infinity?mo('∞'):el('mn',escapeMath(typeof s==='number'?format(s,4):s)),mt=s=>el('mtext',escapeMath(s)),row=s=>el('mrow',s),frac=(a,b)=>el('mfrac',row(a)+row(b)),sup=(a,b)=>el('msup',row(a)+row(b)),sub=(a,b)=>el('msub',row(a)+row(b)),sqrt=a=>el('msqrt',a),paren=s=>mo('(')+s+mo(')'),math=s=>`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">${row(s)}</math>`;
const num=x=>x<0&&Number.isFinite(x)?paren(mn(x)):mn(x),idx=(a,b)=>sub(mi(a),mt(b));
const sum=(n,expr)=>el('munderover',mo('∑')+row(mi('k')+mo('=')+mn(0))+row(mn(n-1)))+expr;
export function derivation(m,calc){
 if(!calc)return'';const t=calc.tensor,a=m.tensors.get(t.inputs[0]),b=m.tensors.get(t.inputs[1]),r=calc.row,c=calc.col,A=idx('a',`${r},${c}`),B=idx('b',`${r},${c}`),Y=idx('y',`${r},${c}`),v=(tt,rr=r,cc=c)=>tt?.values[rr]?.[cc],eq=mo('='),plus=mo('+'),times=mo('×');let symbolic='',numeric='',legend='a: input coordinate · y: output coordinate.';
 const term=(body,i)=>`<mrow class="term" data-term="${i}">${body}</mrow>`;
 if(t.op==='matmul'){const n=a.shape[1];symbolic=Y+eq+sum(n,idx('A',`${r},k`)+idx('B',`k,${c}`));numeric=calc.terms.map((q,i)=>term(num(q.a.value)+times+num(q.b.value),i)).join(plus);legend=`A: ${a.label}. B: ${b.label}. Multiply a row by a column; sum ${n} products. Indices start at zero.`;}
 else if(['add','sub','bias'].includes(t.op)){symbolic=Y+eq+A+mo(t.op==='sub'?'−':'+')+(t.op==='bias'?idx('b',c):B);numeric=num(v(a))+mo(t.op==='sub'?'−':'+')+num(v(b,t.op==='bias'?0:r));legend=t.op==='bias'?'b is a learned bias, shared across token positions.':'Matching coordinates are combined; the tensor shape is unchanged.';}
 else if(t.op==='scale'){symbolic=Y+eq+frac(A,mi('s'));numeric=frac(num(v(a)),num(t.divisor));legend='s is the divisor for this operation. Dividing embeddings by 1/√d is equivalent to multiplying by √d.';}
 else if(t.op==='multiplyScalar'){symbolic=Y+eq+mi('η')+A;numeric=num(t.scalar)+times+num(v(a));legend='η is the learning rate; a is the gradient after clipping.';}
 else if(['rowSum','rowMean','mean'].includes(t.op)){const n=calc.terms.length,expression=sum(n,idx('a','k')),values=calc.terms.map((q,i)=>term(num(q.a.value),i)).join(plus);symbolic=Y+eq+(t.op==='rowSum'?expression:frac(expression,mn(n)));numeric=t.op==='rowSum'?values:frac(values,mn(n));legend=t.op==='rowSum'?'Sum all entries in this row.':'Average the contributing values; the divisor is the number of terms.';}
 else if(['rowDivide','rowSubtract'].includes(t.op)){symbolic=Y+eq+(t.op==='rowDivide'?frac(A,idx('s',r)):A+mo('−')+idx('s',r));numeric=t.op==='rowDivide'?frac(num(v(a)),num(v(b,r,0))):num(v(a))+mo('−')+num(v(b,r,0));legend=t.normalization?'s is this token’s normalization statistic.':'s is a row statistic: the maximum before exponentiation, or the exponential sum before normalization.';}
 else if(t.op==='affine'){symbolic=Y+eq+idx('γ',c)+A+plus+idx('β',c);numeric=num(v(b,0))+times+num(v(a))+plus+num(m.tensors.get(t.inputs[2]).values[0][c]);legend='γ and β are learned scale and offset for each feature.';}
 else if(t.op==='exp'){symbolic=Y+eq+sup(mi('e'),A);numeric=sup(mi('e'),num(v(a)));legend='e is Euler’s number. Exponentiating −∞ gives zero, removing a masked key.';}
 else if(t.op==='square'){symbolic=Y+eq+sup(A,mn(2));numeric=sup(paren(num(v(a))),mn(2));legend='Squaring makes positive and negative deviations contribute to the spread.';}
 else if(t.op==='std'){symbolic=Y+eq+sqrt(A+plus+mi('ε'));numeric=sqrt(num(v(a))+plus+mn(0.00001));legend='a is the variance. ε = 0.00001 protects the denominator from zero.';}
 else if(t.op==='relu'){symbolic=Y+eq+mi('max')+paren(mn(0)+mo(',')+A);numeric=mi('max')+paren(mn(0)+mo(',')+num(v(a)));legend='A positive input passes unchanged; a negative input becomes zero.';}
 else if(t.op==='neglog'){symbolic=idx('ℓ',r)+eq+mo('−')+mi('ln')+paren(idx('p','target'));numeric=mo('−')+mi('ln')+paren(num(v(a)));legend='Natural logarithm gives loss in nats. Lower probability on the correct target creates a larger loss.';}
 else if(t.op==='rowmax'){symbolic=idx('s',r)+eq+mi('max')+paren(idx('a','r,0')+mo(',')+mo('…'));numeric=mi('max')+paren(a.values[r].map(num).join(mo(',')));legend='The maximum is subtracted from every score in the row to stabilize exponentiation.';}
 else if(t.op==='position'){const i=Math.floor(c/2),fn=c%2?'cos':'sin';symbolic=idx('PE',`p,${c}`)+eq+mi(fn)+paren(frac(mi('p'),sup(mn(10000),frac(mn(2*i),mi('d')))));numeric=mi(fn)+paren(frac(mn(r),sup(mn(10000),frac(mn(2*i),mn(4)))));legend='p is token position, d = 4. Even coordinates use sine; odd coordinates use cosine.';}
 else if(t.op==='transpose'){symbolic=sub(sup(mi('K'),mi('T')),mt(`${r},${c}`))+eq+idx('K',`${c},${r}`);numeric=mn(v(a,c,r));legend='T means transpose: exchange indices without changing a value.';}
 else if(t.op==='mask'){symbolic=Y+eq+A+plus+idx('M',`${r},${c}`);numeric=num(v(a))+plus+(t.allowed[r][c]?mn(0):mo('−')+mo('∞'));legend='M is zero for allowed keys and negative infinity for forbidden keys.';}
 else if(t.op==='lookup'){symbolic=idx('x',`${r},${c}`)+eq+idx('E',`${t.indices[r]},${c}`);numeric=mn(calc.result);legend='E is the learned embedding table. A token ID selects one row, not a semantic score.';}
 else if(t.op==='backward'||t.op==='gradient'){symbolic=frac(mi('∂')+mi('L'),mi('∂')+mi('x'))+eq+sum(calc.terms.length,frac(mi('∂')+mi('L'),mi('∂')+idx('y','k'))+frac(mi('∂')+idx('y','k'),mi('∂')+mi('x')));numeric=calc.terms.map((q,i)=>term(num(q.upstream??q.value)+times+num(q.derivative??1),i)).join(plus);legend='L is loss. Each path contributes its incoming gradient multiplied by its local derivative.';}
 else{symbolic=Y+eq+mt(t.op==='tokens'?'vocabulary lookup':t.op==='concat'?'selected head coordinate':t.op==='gather'?'probability of target':t.label);numeric=mn(calc.result);}
 return `<div class="derivation"><span class="math-caption">GENERAL RULE</span>${math(symbolic)}<p class="symbol-key">${escapeMath(legend)}</p><span class="math-caption">SUBSTITUTE THE LIVE VALUES</span><div class="numeric-derivation">${math(numeric+eq+mn(calc.result))}</div><p class="math-rounding">Displayed values are rounded; computation uses full precision.</p></div>`;
}
// Typeset known indices inside native SVG text, without converting the diagram to an image.
export function svgSymbols(s){return escapeMath(s).replace(/\b(W|d|x|q|k|v)_(model|[QKVO]|[0-9]+|k)\b/g,'$1<tspan baseline-shift="sub" font-size="72%">$2</tspan>').replace(/\b([xqkv])([0-9])\b/g,'$1<tspan baseline-shift="sub" font-size="72%">$2</tspan>');}
