import {svgSymbols} from './math.js?v=expanded-space-2';
import {format} from './course.js?v=expanded-space-2';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=(x,y,s,size=15,color='#bcdad5')=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}" text-anchor="middle">${svgSymbols(s)}</text>`;
export function neuronPhase(id,p){return id.endsWith('.expand')?Math.min(3,Math.floor(p*4)):id.endsWith('.biased')?4:id.endsWith('.relu')?5:6;}
export function neuronState(m,id,row=0,neuron=0,step=0){
 const prefix=id.match(/^(enc|dec)\.\d+\.ff/)?.[0]||'enc.0.ff',get=s=>m.tensors.get(s),expand=get(prefix+'.expand'),input=get(expand.inputs[0]),r=Math.min(row,input.shape[0]-1),j=neuron%8,x=input.values[r],w=get('@'+prefix+'.W1').values.map(v=>v[j]),products=x.map((v,i)=>v*w[i]),bias=get('@'+prefix+'.b1').values[0][j],sum=products.reduce((a,b)=>a+b,0),z=sum+bias,h=Math.max(0,z),output=get(prefix+'.bias').values[r],weights2=get('@'+prefix+'.W2').values[j];
 return {prefix,row:r,neuron:j,step,x,w,products,bias,sum,z,h,output,weights2,hidden:get(prefix+'.relu').values[r],partial:products.slice(0,Math.min(4,step+1)).reduce((a,b)=>a+b,0)};
}
export function neuronMarkup(s){
 const {x,w,products,neuron:j,step,z,h}=s;let out=txt(500,133,`NEURON MICROSCOPE · token ${s.row} · hidden neuron ${j}`,14,'#edcf85');
 for(let i=0;i<4;i++){const y=185+i*65,active=step===i,done=step>=i;out+=`<path d="M175 ${y}H363L490 281" fill="none" stroke="${active?'#acffdc':'#36514c'}" stroke-width="${active?3:1}"/><circle cx="125" cy="${y}" r="28" fill="#071813" stroke="#77bda9"/>${txt(125,y+5,format(x[i],3))}${txt(263,y-12,`× ${format(w[i],3)}`,16,active?'#efcf7d':'#7eaaa0')}<rect x="319" y="${y-18}" width="87" height="36" rx="7" fill="${active?'#153a2b':'#060d0b'}" stroke="${active?'#abffdc':'#32443f'}"/>${txt(362,y+5,done?format(products[i],3):'…',15)}${txt(69,y+5,'x'+i,12,'#75988f')}`;}
 out+=`<circle cx="525" cy="281" r="36" fill="#10251d" stroke="#e4cb7c" stroke-width="2"/>${txt(525,276,'Σ',27,'#e4cb7c')}${txt(525,298,format(step<4?s.partial:s.sum,3),13)}<path d="M563 281H626" stroke="#9ac7b5"/><rect x="628" y="246" width="134" height="70" rx="12" fill="${step===4?'#302719':'#0b1210'}" stroke="#d1b76b"/>${txt(695,269,'+ bias '+format(s.bias,3),14,'#edcf85')}${txt(695,296,step>=4?format(z,4):'waiting',17)}<path d="M763 281H804" stroke="#9ac7b5"/><rect x="807" y="246" width="143" height="70" rx="12" fill="${z<=0?'#281419':'#112c20'}" stroke="${z<=0?'#d18692':'#87dfb4'}"/>${txt(879,270,'ReLU · max(0, z)',13)}${txt(879,296,step>=5?format(h,4):'waiting',18,'#abffdb')}`;
 // The gate graph is plotted in local numerical coordinates and includes the actual activation.
 const scale=48/Math.max(1,Math.abs(z));out+=`<path d="M799 403H946M859 417V340" stroke="#436358"/><path d="M803 398H859L916 341" fill="none" stroke="#8ddeb4" stroke-width="2"/><circle cx="${859+z*scale}" cy="${398-h*scale}" r="6" fill="#f5d587"/>${txt(874,438,z>0?'Positive signal passes unchanged':'Negative signal becomes zero',12,'#c7aaae')}`;
 out+=txt(590,366,'Inspect any of the 8 hidden neurons',12,'#749b90');for(let k=0;k<8;k++)out+=`<g data-neuron="${k}" role="button" tabindex="0" aria-label="Inspect hidden neuron ${k}" style="cursor:pointer"><circle cx="${449+k*39}" cy="394" r="16" fill="${k===j?'#315b3e':'#0d1b16'}" stroke="${k===j?'#dcda8b':'#4b7965'}"/>${txt(449+k*39,399,k,12)}</g>`;
 out+=txt(480,469,step<4?`Input ${step}: ${format(x[step],4)} × ${format(w[step],4)} = ${format(products[step],4)}`:step===4?`Σ products ${format(s.sum,4)} + bias ${format(s.bias,4)} = ${format(z,4)}`:step===5?`ReLU(${format(z,4)}) = ${format(h,4)} · local derivative ${z>0?1:0}`:`This neuron contributes ${format(h,3)} × ${format(s.weights2[0],3)} = ${format(h*s.weights2[0],4)} to output feature 0`,16,'#e4d396');return out;
}
export function neuronNarrative(s){const i=Math.min(3,s.step);return s.step<4?{title:`Multiply feature ${i} by its learned connection`,how:`Input ${format(s.x[i],5)} × weight ${format(s.w[i],5)} = ${format(s.products[i],5)}. The running sum is ${format(s.partial,5)}.`,why:'A neuron combines all four features. The sign of a weight controls whether this feature adds to or subtracts from the response.'}:s.step===4?{title:'Shift the activation with a bias',how:`The complete dot product is ${format(s.sum,5)}. Adding bias ${format(s.bias,5)} gives z = ${format(s.z,5)}.`,why:'The bias sets a learned offset, so activation need not be determined only by a boundary through the origin.'}:s.step===5?{title:s.z>0?'The ReLU gate opens':'The ReLU gate closes',how:`max(0, ${format(s.z,5)}) = ${format(s.h,5)}. Its local derivative is ${s.z>0?1:0}; at zero this model uses zero.`,why:'Without a nonlinear gate, the two linear layers would collapse to one affine map. ReLU allows different input regions to receive different transformations.'}:{title:'Project all eight hidden responses back to four features',how:`Neuron ${s.neuron} contributes ${format(s.h*s.weights2[0],5)} to output feature 0. The other seven contributions and the output bias produce ${format(s.output[0],5)}.`,why:'The next residual addition requires the original four-feature width. The same network is applied independently to each token, with shared weights.'};}
export class LiveNarrative{
 constructor(){this.el=document.createElement('section');this.el.className='live-microscope';this.el.innerHTML='<span>INSIDE THIS OPERATION</span><h3></h3><p class="micro-how"></p><p class="micro-why"></p>';document.querySelector('#lesson-explanation')?.prepend(this.el);}
 update(s){this.el.hidden=!s;if(!s)return;const key=JSON.stringify(s);if(key===this.key)return;this.key=key;this.el.querySelector('h3').textContent=s.title;this.el.querySelector('.micro-how').textContent=s.how;this.el.querySelector('.micro-why').textContent=s.why;}
}
export function normPhase(id){return /\.(center)$/.test(id)?1:/\.(squared|variance)$/.test(id)?2:/\.(std|unit)$/.test(id)?3:id.endsWith('.norm.output')?4:0;}
export function normState(m,id,row=0,step=0){const prefix=id.includes('.norm.')?id.split('.norm.')[0]:id.replace(/\.residual$/,''),get=s=>m.tensors.get(prefix+s),r=Math.min(row,get('.residual').shape[0]-1);return {row:r,step,x:get('.residual').values[r],mean:get('.norm.mean').values[r][0],center:get('.norm.center').values[r],squared:get('.norm.squared').values[r],variance:get('.norm.variance').values[r][0],std:get('.norm.std').values[r][0],unit:get('.norm.unit').values[r],out:get('.norm.output').values[r]};}
export function normMarkup(s){const labels=['Residual features','Subtract the mean','Square deviations','Divide by standard deviation','Learned scale + shift'],values=[s.x,s.center,s.squared,s.unit,s.out],active=Math.min(4,s.step),v=values[active],max=Math.max(1,...values.flat().map(Math.abs)),scale=90/max;let out=txt(500,137,`NORMALIZATION MICROSCOPE · token ${s.row}`,14,'#edcf85');for(let k=0;k<5;k++){const x=110+k*195;out+=`<rect x="${x-80}" y="161" width="160" height="35" rx="7" fill="${k===active?'#214732':'#09140f'}" stroke="${k===active?'#a7f4cb':'#2c4439'}"/>${txt(x,183,labels[k],11)}`;}
 out+=txt(500,236,labels[active],23,'#d6ecdf')+'<path d="M125 355H875" stroke="#507366"/>';v.forEach((value,i)=>{const x=240+i*173,height=Math.abs(value)*scale;out+=`<rect x="${x-35}" y="${value>=0?355-height:355}" width="70" height="${Math.max(1,height)}" rx="4" fill="${value>=0?'#4cba90':'#bc7084'}" fill-opacity=".65"/>${txt(x,343-height,format(value,4),15,'#ecdcac')}${txt(x,442,'feature '+i,12,'#91b6a6')}`;});
 out+=txt(500,473,`μ = ${format(s.mean,4)}    σ² = ${format(s.variance,4)}    √(σ² + ε) = ${format(s.std,4)}`,17,'#e4cf91');return out;}
export function normNarrative(s){const titles=['Start with one token’s residual row','Center each feature around zero','Measure feature spread','Standardize the row','Restore learned scale and offset'],how=[`Row ${s.row}: [${s.x.map(v=>format(v,3)).join(', ')}]. Its mean is ${format(s.mean,5)}.`,`Subtract ${format(s.mean,5)} from every feature. Centered values: [${s.center.map(v=>format(v,3)).join(', ')}].`,`Square each centered value, then average all four squares. Variance = ${format(s.variance,5)}.`,`Divide by √(variance + 0.00001) = ${format(s.std,5)}. The small epsilon prevents division by zero.`,`Multiply normalized features by learned γ and add learned β. Output: [${s.out.map(v=>format(v,3)).join(', ')}].`];return {title:titles[s.step],how:how[s.step],why:'Layer normalization computes statistics across the features of one token, not across tokens. It controls the scale seen by the next sublayer while learned scale and offset retain flexibility.'};}
export function attentionMarkup(m,t,row=0){const prefix=t.id.replace(/\.(max|shift|exp|sum|A)$/,''),get=s=>m.tensors.get(prefix+'.'+s),r=Math.min(row,t.shape[0]-1),scores=get('masked').values[r],shift=get('shift').values[r],exp=get('exp').values[r],weights=get('A').values[r],max=get('max').values[r][0],sum=get('sum').values[r][0];let body=txt(500,139,`QUERY ${r} · stabilize → exponentiate → normalize`,16,'#edd18e');const titles=['Masked score','Subtract row max','Exponential','Divide by row sum'];titles.forEach((title,i)=>body+=txt(140+i*240,179,title,15,'#97b8ad'));for(let j=0;j<scores.length;j++){const spacing=Math.min(49,192/Math.max(1,scores.length)),cellHeight=Math.min(37,spacing-4),y=222+j*spacing;const values=[scores[j],shift[j],exp[j],weights[j]];for(let k=0;k<4;k++){const x=140+k*240;body+=`<g class="softmax-stage" data-softmax="${k}"><rect x="${x-72}" y="${y-cellHeight/2}" width="144" height="${cellHeight}" rx="7" fill="${k===3?'#123023':'#081510'}" stroke="#426751"/>${txt(x,y+5,format(values[k],5),Math.min(15,cellHeight*.46),k===3?'#b2f8cf':'#c9dccf')}</g>`;if(k<3)body+=`<path class="flow-wire" d="M${x+74} ${y}H${x+164}" fill="none" stroke="#79a88e"/>`;}body+=txt(38,y+4,'key '+j,11,'#7e9b8e');}body+=txt(500,446,`row max = ${format(max,5)}     Σ exp(score − max) = ${format(sum,5)}`,17,'#dfcb8e')+txt(500,475,`Subtracting the same maximum preserves softmax; probabilities sum to ${format(weights.reduce((a,b)=>a+b,0),4)}.`,14,'#9dc7b5');return {body,subtitle:'See every key compete for a share of this query’s attention'};}
