import {calculationRibbon,svgFormula,notation} from './math.js?v=math-type-1';
import {neuronState,neuronMarkup,neuronNarrative,neuronPhase,normState,normMarkup,normNarrative,normPhase} from './microscope.js?v=math-type-1';
import {demoHeatmap} from './reference-designs.js?v=math-type-1';
import {calculate,format} from './course.js?v=math-type-1';
import {clamp} from './space.js?v=math-type-1';
const NS='http://www.w3.org/2000/svg';
function node(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function updateMathLabel(el,source){if(!el)return;let host=el;if(el.tagName.toLowerCase()==='text'){host=node('g',{'class':el.getAttribute('class')||''});host.innerHTML=svgFormula(+el.getAttribute('x'),+el.getAttribute('y'),notation(source),+el.getAttribute('font-size')||20,el.getAttribute('fill')||'#b9e9dc',930,55);el.replaceWith(host);}else if(host.dataset.formula!==source)host.querySelector('.equation-html').innerHTML=notation(source);host.dataset.formula=source;}
export function operationFrame(model,tensor,row,col,termIndex,fraction){const calc=calculate(model,tensor,row,col);if(!calc)return null;const index=Math.max(0,termIndex)%calc.terms.length,term=calc.terms[index];return {calc,index,term,fraction:clamp(fraction),partial:calc.terms.slice(0,index+1).reduce((s,x)=>s+x.value,0)};}
// Animate actual operands through a local operation. No screenshot fades or page transforms.
export class OperationMotion{
 constructor(host){this.host=host;}
 bind(model,scene,options){this.ribbonKey='';this.model=model;this.scene=scene;this.options=options;this.svg=this.host.querySelector('svg');if(!this.svg)return;this.layer=node('g',{'class':'operation-motion','pointer-events':'none'});this.svg.append(this.layer);this.cells=[...this.svg.querySelectorAll('[data-tensor]')];this.neural=this.svg.querySelector('.neural-microscope');this.norm=this.svg.querySelector('.normalization-microscope');this.normKey='';if(this.neuronScene!==scene.id){this.neuronScene=scene.id;this.neuron=(options.col||0)%8;}this.neuralKey='';const choose=ev=>{const el=ev.target.closest('[data-neuron]');if(el&&(ev.type==='click'||ev.key==='Enter'||ev.key===' ')){ev.preventDefault();ev.stopPropagation();this.neuron=+el.dataset.neuron;this.neuralKey='';this.host.dispatchEvent(new CustomEvent('inspect-neuron',{bubbles:true,detail:{index:this.neuron}}));}};this.svg.addEventListener('click',choose);this.svg.addEventListener('keydown',choose);this.links=[...this.svg.querySelectorAll('.flow-wire,.graph-link')].map(path=>({path,length:path.getTotalLength(),dot:node('circle',{r:3.2,fill:path.getAttribute('stroke')||'#c4ffe4'})}));for(const l of this.links)this.layer.append(l.dot);this.packets=[0,1].map(i=>{const g=node('g');g.append(node('circle',{r:18,fill:'#071819',stroke:i?'#edce7c':'#99edce','stroke-width':1.5}));const text=node('text',{'text-anchor':'middle',y:5,fill:i?'#edce7c':'#c6ffe5','font-size':12});g.append(text);this.layer.append(g);return {g,text};});this.readout=node('text',{x:500,y:665,'text-anchor':'middle',fill:'#b8efdd','font-size':15});this.layer.append(this.readout);this.bars=[...this.svg.querySelectorAll('.value-bar')].map(el=>({el,h:+el.getAttribute('height'),y:+el.getAttribute('y'),baseline:+el.dataset.baseline,negative:el.dataset.negative==='true'}));}
 cell(ref){if(!ref)return null;const n=this.cells.find(n=>n.dataset.tensor===ref.tensor&&+n.dataset.row===ref.row&&+n.dataset.col===ref.col);if(!n)return null;const b=n.getBBox();return[b.x+b.width/2,b.y+b.height/2];}
 draw(time,progress=0,paused=false){if(!this.svg)return;const p=paused?1:(time/2.2)%1;
  for(let i=0;i<this.links.length;i++){const l=this.links[i],q=l.path.getPointAtLength(((p+i*.087)%1)*l.length);l.dot.setAttribute('cx',q.x);l.dot.setAttribute('cy',q.y);l.dot.style.opacity=paused?'0':'.9';}
  const o=this.options,frame=this.scene.visualOnly?null:operationFrame(this.model,this.scene.tensor,o.row||0,o.col||0,o.term||0,p);
  this.packets.forEach(x=>x.g.style.display='none');this.readout.textContent='';
  if(frame){const {term,calc}=frame,refs=[term.a,term.b].filter(Boolean),target=this.cell({tensor:calc.tensor.id,row:o.row||0,col:o.col||0})||[500,550];
   refs.forEach((ref,i)=>{if(i===1&&p>=.55)return;let from=this.cell(ref);if(!from&&calc.tensor.op==='lookup'){const token=this.svg.querySelectorAll('.token-asset')[o.row||0];if(token){const box=token.getBBox();from=[box.x+box.width/2,box.y+box.height/2];}}if(!from)return;const to=p<.55?[500,481]:target,u=p<.55?p/.55:(p-.55)/.45,origin=p<.55?from:[500,481],x=origin[0]+(to[0]-origin[0])*u,y=origin[1]+(to[1]-origin[1])*u-Math.sin(u*Math.PI)*20;this.packets[i].g.style.display=paused?'none':'';this.packets[i].g.setAttribute('transform',`translate(${x},${y})`);this.packets[i].text.textContent=format(p<.55?ref.value:term.value,2);});
   // The shared MathML ribbon below the assets displays this term and its running sum.
  }
  // Construct bar magnitudes from their computed values while preserving sign.
  const fill=1;for(const b of this.bars){b.el.setAttribute('height',b.h*fill);b.el.setAttribute('y',b.negative?b.baseline:b.baseline-b.h*fill);}
  const n=this.scene.reference;if([35,36,37].includes(n)){const step=paused?6:Math.min(6,Math.floor((time%10)/1.3)),retention=.75**step;const bar=this.svg.querySelector('.memory-bar');if(bar)bar.setAttribute('width',850*retention);const label=this.svg.querySelector('.memory-value');updateMathLabel(label,`{∂h_${step}}/{∂h_0} = 0.75^{${step}} = ${retention.toFixed(3)}`);this.svg.querySelectorAll('.recurrent-token').forEach((el,i)=>{el.querySelector('rect').setAttribute('fill',i===step?'#214733':'#071014');});}
  if(n===33){const count=paused?4:Math.min(4,Math.floor((time%10)/2)),value=count*12288*128;this.svg.querySelectorAll('.parameter-row').forEach((el,i)=>el.style.opacity=i<count?'1':'.3');updateMathLabel(this.svg.querySelector('.parameter-sum'),`${count} × 12288 × 128 = ${value}`);}
  if(n===54||n===55){const demo=demoHeatmap(),i=paused?0:Math.floor(time/1.5)%6,j=n===55?i:paused?0:Math.floor(time/.25)%6;this.svg.querySelectorAll('.demo-attention-cell').forEach(el=>{const active=+el.dataset.query===i&&+el.dataset.key===j;el.querySelector('rect').setAttribute('stroke-width',active?'3':'1');el.querySelector('rect').setAttribute('stroke',active?'#f5dc8c':'#695382');});updateMathLabel(this.svg.querySelector('.demo-score-readout'),`q = [${demo.vectors[i]}], k = [${demo.vectors[j]}], {q⋅k}/√2 = ${demo.scores[i][j].toFixed(4)}`);updateMathLabel(this.svg.querySelector('.demo-weight-readout'),`a_{${i},${j}} = ${demo.weights[i][j].toFixed(5)}`);}
  if(n===1)this.svg.querySelectorAll('.subword-piece rect').forEach((el,i)=>el.setAttribute('stroke-width',!paused&&Math.floor(time*1.2)%7===i?'3':'1.3'));
  if(frame){this.cells.forEach(el=>{el.classList.toggle('motion-operand',[frame.term.a,frame.term.b].some(r=>r&&r.tensor===el.dataset.tensor&&r.row===+el.dataset.row&&r.col===+el.dataset.col));});}
  if(this.neural){const step=neuronPhase(this.scene.tensor,paused?1:progress),state=neuronState(this.model,this.scene.tensor,o.row||0,this.neuron,step),key=JSON.stringify(state);if(key!==this.neuralKey){this.neural.innerHTML=neuronMarkup(state);this.neuralKey=key;}this.narrative=neuronNarrative(state);if(!paused){const packet=this.packets[0],u=p;let from,to,value;if(step<4){from=[175,185+step*65];to=[525,281];value=u<.45?state.x[step]:state.products[step];}else{from=step===4?[562,281]:[762,281];to=step===4?[695,281]:[879,281];value=step===4?state.z:state.h;}packet.g.style.display='';packet.g.setAttribute('transform',`translate(${from[0]+(to[0]-from[0])*u},${from[1]+(to[1]-from[1])*u})`);packet.text.textContent=format(value,2);}}else this.narrative=frame?{title:'Follow contribution '+(frame.index+1)+' of '+frame.calc.terms.length,how:frame.term.label+' = '+format(frame.term.value,6)+(frame.calc.additive?'. Running sum: '+format(frame.partial,6)+'.':''),why:frame.calc.additive?'Each contribution must be included. The highlighted operands feed this term; the complete sum creates the selected output coordinate.':this.scene.how}:null;
  if(this.norm){const step=normPhase(this.scene.tensor),state=normState(this.model,this.scene.tensor,o.row||0,step),key=JSON.stringify(state);if(key!==this.normKey){this.norm.innerHTML=normMarkup(state);this.normKey=key;}this.narrative=normNarrative(state);}
  if(frame){this.svg.querySelectorAll('.product-asset').forEach((el,i)=>{el.classList.toggle('active-product',i===frame.index);el.querySelector('rect').setAttribute('stroke',i===frame.index?'#edce79':'#264046');el.style.opacity=frame.calc.additive&&i>frame.index?'.4':'1';});const sum=this.svg.querySelector('.accumulation-readout .equation-html');if(sum){const key=frame.index+':'+frame.calc.result;if(key!==this.ribbonKey){this.ribbonKey=key;sum.innerHTML=calculationRibbon(frame.calc,frame.index);}}}
  const neurons=[...this.svg.querySelectorAll('.neuron')];neurons.forEach(el=>{const active=paused||Math.floor(time*1.2)%3===+el.dataset.layer;el.querySelector('circle').setAttribute('stroke-width',active?'3':'1');});
 return frame;
 }
}
