// Original explanatory copy; figure topology and section references follow Vaswani et al.
export const introduction=[
 ['world','What is a Transformer?','all','A sentence is more than separate words. To translate it, a model must represent relationships, preserve order, and choose a coherent sequence of output words.','A Transformer is a learned sequence-to-sequence model. Its encoder builds contextual representations of the input; its decoder uses those representations and the output prefix to predict the next token.','The diagram is the original encoder–decoder design. Follow it from the inputs at the bottom to the probability distribution at the top. The blocks will stay in place throughout this lesson.'],
 ['problem-context','Why translating word by word is not enough.','enc.self','“The cat chased the dog” and “The dog chased the cat” contain the same words but describe different events. A bag of word meanings loses who did what to whom.','Each token needs a representation that depends on other tokens and its position. The encoder combines learned features with order information, then lets positions exchange relevant information.','Context changes the representation, not the token’s identity. The decoder can then use these contextual features when choosing words in the other language.'],
 ['problem-recurrence','Why remove recurrence?','enc.self','A recurrent model computes a state from the previous state. That dependence creates a chain: later positions must wait for earlier ones during a training example. Distant information travels through many intermediate positions.','The paper replaces that recurrence with self-attention. All input positions can form queries, keys and values together; a query can compare directly with a distant key.','This shortens the interaction path and permits parallel computation across known input positions. It does not make autoregressive generation parallel: newly generated output tokens still arrive one at a time.'],
 ['solution-attention','Let the relevant words communicate directly.','enc.self','A token should not receive the same mixture of context in every sentence. Which other positions matter depends on the current representations and on what the model has learned.','Attention computes a score for each query–key pair, normalizes the visible scores into weights, and uses those weights to combine value vectors. The routing is data-dependent.','The output at each position is a weighted mixture of information. It is not a hard lookup, and an attention weight alone is not a complete explanation of the model’s decision.'],
 ['two-stacks','Two stacks, two different jobs.','all','The source sentence is fully available, but the future translation is not. Treating both sides identically would let the decoder read answers that are unavailable when it generates.','The encoder reads all unpadded source positions. The decoder first attends to its known output prefix, then attends to the encoder’s final memory through a separate cross-attention sublayer.','Trace the bridge from the left stack into the middle attention block on the right. That block gets keys and values from the encoder, and queries from the decoder.'],
 ['paper-dimensions','One diagram describes a repeated stack.','all','One pass may not be enough to build useful features. Stacking blocks lets later layers reinterpret the representations produced by earlier ones.','N× means repeat the entire enclosed block. The paper’s base model uses N = 6, 512 features, 8 heads and 2,048 feed-forward features. Each layer has its own learned parameters.','Our numerical lens uses 1 or 2 blocks, 4 features, 2 heads and 8 feed-forward features so the arithmetic stays inspectable. The architecture is the same pattern; these are not the paper’s trained weights.'],
 ['known-example','Start with one consistent example.','source.embedding','To see causality in the computation, every stage must use the same numbers. Decorative scores that change independently would hide how an input affects the prediction.','We use “the cat sleeps” → “le chat dort <eos>”. The source embeddings begin at [0.2, −0.5, 0.8, 0.1], [0.9, 0.3, −0.2, 0.7], and [−0.1, 0.6, 0.4, −0.8]. Other parameters use a fixed seed.','The model begins untrained. Edit an embedding or weight and the whole computation runs again. Follow the changing result, then use actual gradient updates to fit this tiny example.']
].map(([id,title,focus,why,how,result])=>({id,tensor:'world',title,focus,why,how,result,body:why,concept:'architecture',group:'01 / THE PROBLEM & THE IDEA',length:1.65}));
export const paperLessons=[
 ['paper-parallel','What becomes parallel—and what does not.','enc.self','The motivation is to reduce sequential work, not to eliminate every dependency. Confusing training with generation makes this distinction easy to miss.','During teacher-forced training, known shifted target tokens allow all decoder positions to be evaluated together under a causal mask. At inference, a new token must be selected before it can join the prefix.','Full self-attention compares every pair of positions, so its attention matrix has n² entries. Short paths and parallel work come with a quadratic sequence-length cost.'],
 ['paper-dropout','Why the paper adds dropout.','enc.ff','A large model can rely too strongly on particular internal features and fit training examples without generalizing well.','During training, dropout randomly removes some contributions. The original architecture applies it to sublayer outputs before residual addition and normalization, and to sums of embeddings and positional encodings.','The paper’s base dropout probability is 0.1. Dropout is disabled at inference. This miniature omits it to make repeated numerical calculations deterministic; the glowing paths are not dropout samples.'],
 ['paper-smoothing','Why avoid perfectly one-hot training targets?','output.softmax','Requiring probability one on the observed target encourages extreme confidence. A slightly softened target distribution can act as a regularizer.','Label smoothing moves some probability mass away from the single target. The paper uses smoothing value 0.1. Its training objective therefore differs from pure hard-target negative log-likelihood.','The live miniature uses hard targets so −log p(target) is transparent. Its displayed loss is not the original paper’s label-smoothed training loss.'],
 ['paper-optimizer','How the paper trains the weights.','all','Different parameters can have very different gradient scales. Large updates early in training may also destabilize an otherwise useful model.','The paper uses Adam with β₁ = 0.9, β₂ = 0.98 and ε = 10⁻⁹. Its learning rate first warms up for 4,000 steps, then decreases proportional to the inverse square root of the step number.','The learning-rate formula is d_model⁻¹ᐟ² × min(step⁻¹ᐟ², step × warmup⁻³ᐟ²). Our live controls use simpler clipped SGD, explicitly shown as a teaching experiment.'],
 ['paper-results','What the experiments established.','output.softmax','An architecture needs evaluation on held-out data; a visually convincing attention map or a memorized sentence does not establish translation quality.','The paper evaluated machine translation and also constituency parsing. Its reported big-model translation scores included 28.4 BLEU for English–German and 41.8 for English–French on the cited WMT 2014 tasks.','Those are historical results from the paper, not scores produced here. Training one sentence in this browser demonstrates the mechanics of learning, not comparable generalization.'],
 ['complete','Now read the whole architecture as one computation.','all','Each block solves part of the original problem: representing words, preserving order, exchanging context, preventing leakage, transforming features, and choosing a next token.','Start below the encoder and follow the arrows. Then start below the decoder, pass through masked attention, cross the encoder-memory bridge, and continue through the linear projection and softmax.','You can select a block to return to its explanation. Atlas contains every internal calculation and all 70 supplied reference concepts; Experiment lets you change the same model and observe the consequences.']
].map(([id,title,focus,why,how,result])=>({id,tensor:'world',title,focus,why,how,result,body:why,concept:'training',group:'THE PAPER / TRAINING, EVIDENCE & LIMITS',length:1.7}));
const reasons={
 tokens:'A neural network cannot multiply words directly. Discrete token IDs give it a consistent address into a learned vocabulary table; the numerical size of an ID carries no semantic meaning.',
 lookup:'One-hot IDs do not provide a useful feature space on their own. A learned embedding gives each token a compact vector that training can adapt to the task.',
 position:'Attention without position information treats a rearrangement of tokens as the same set of token representations. Translation needs order, so the model must receive positional information.',
 transpose:'The dot-product implementation needs feature dimensions to meet on the inner axis. Transposing keys makes the matrix product compare each query with every key.',
 mask:'The model must not depend on information that is unavailable or artificial. Padding is not a real word; future target tokens are not known at generation time.',
 rowmax:'Exponentiating a large positive score can overflow. Subtracting a shared maximum leaves all softmax ratios unchanged while making the calculation numerically stable.',
 rowSubtract:'Removing a shared row statistic changes the reference point while preserving the differences that the next operation needs.',
 exp:'Raw scores can be negative and do not form mixture weights. Exponentiation turns finite scores into positive relative strengths; a masked −∞ becomes exactly zero.',
 rowSum:'A weight has meaning relative to all visible alternatives. The denominator measures their total exponential strength so the next operation can allocate one unit of probability.',
 rowDivide:'The result needs a controlled scale: attention needs weights summing to one, while normalization needs standardized feature magnitudes.',
 concat:'Different heads can preserve different learned comparisons and mixtures. Averaging them immediately would collapse these distinctions; concatenation retains their separate coordinates.',
 add:'A sublayer should contribute an update without forcing all prior information through that transformation. The residual route also provides a direct path for gradients.',
 rowMean:'Normalization requires a reference value for each token. Averaging across its features finds that reference without mixing the statistics of different token positions.',
 square:'Positive and negative deviations would cancel if added directly. Squaring makes both contribute to a nonnegative measure of feature variation.',
 std:'Dividing by variance would distort the units of the features. Its square root supplies a scale in the original units; ε prevents division by zero.',
 affine:'Fixed standardization can erase a useful scale or offset. Learned γ and β let the model restore a task-appropriate transformation after normalization.',
 relu:'Two consecutive linear maps collapse into one linear map. A nonlinearity lets the feed-forward block represent transformations that a single linear projection cannot.',
 bias:'A projection alone passes through the origin. A learned bias lets the model shift a feature’s response independently of the current input.',
 gather:'The full vocabulary distribution includes many alternatives, but supervised learning must identify which next token the example asks for at each position.',
 neglog:'We need a scalar penalty that increases when the correct token receives little probability. Negative log-likelihood supplies that penalty and a differentiable training signal.',
 mean:'An average gives one loss for the complete example and a consistent scale for differentiation across its target positions.',
 backward:'Learning requires credit assignment: how would a small change here affect the final loss? The chain rule carries that sensitivity backward through each consumer of a value.',
 gradient:'A weight is reused at multiple positions. Its gradient must include every path from those uses to the loss; taking only one contribution would give an incomplete update.',
 multiplyScalar:'A gradient gives direction and sensitivity, not a safe step size. The learning rate controls how far each parameter moves on this update.',
 sub:'To reduce the local first-order approximation to the loss, gradient descent moves against the gradient. This preview makes that subtraction inspectable before an update is applied.',
 scale:'The magnitude of representations changes how later nonlinear operations behave. Explicit scaling keeps that magnitude appropriate for the stage being computed.',
 matmul:'A learned linear map recombines existing coordinates into a new feature space. Each output coordinate uses one weight column and sums its contributions from the input features.'
};
export function teach(t,m,how){
 let why=reasons[t.op]||'This operation prepares the representation needed by the next block in the architecture.';
 if(t.id.endsWith('.Q'))why='A query expresses what a position is looking for in this learned attention space. Its projection must be separate from keys and values so matching and carried information can play different roles.';
 if(t.id.endsWith('.K'))why='A key provides the features against which queries are compared. In cross-attention these descriptions belong to encoder memory, allowing a decoder position to find relevant source context.';
 if(t.id.endsWith('.V'))why='The features used to choose a source position need not be the features that position contributes. Values separate the content being mixed from the query–key matching calculation.';
 if(t.id.endsWith('.scores'))why='Before combining context, each query needs a compatibility score for each key. A dot product makes aligned learned coordinates reinforce one another; a score is not yet a probability.';
 if(t.id.endsWith('.scaled')&&t.attention)why='As the key dimension grows, unscaled dot products tend to grow in magnitude. Dividing by √d_k reduces that growth so softmax is less likely to saturate and suppress useful gradients.';
 if(t.id.endsWith('.Z'))why='Scores alone do not update the representation. The model needs the information at the attended positions, so each attention weight multiplies a value feature and the contributions are summed.';
 if(t.id.endsWith('.ff.expand'))why='Attention exchanges information between positions. The feed-forward network instead transforms the features within each position; expanding its hidden width creates more intermediate combinations.';
 if(t.id.endsWith('.ff.contract'))why='The expanded hidden features must return to d_model coordinates. That restores the shape required for the residual addition and the next Transformer block.';
 if(t.id==='source.input'||t.id==='target.input')why='Meaning and order must both reach attention. Adding equally sized embeddings and positional vectors supplies both without changing the feature dimension.';
 if(t.normalization&&t.op==='rowDivide')why='A sublayer can change the overall scale of a token’s features. Dividing centered values by that token’s standard deviation keeps the next transformation better conditioned.';
 if(t.id==='output.project')why='The decoder’s four internal features are not vocabulary probabilities. A learned projection gives every possible next token its own score from that representation.';
 if(t.id==='learn.clipped')why='An unusually large global gradient can make a fixed learning rate take an unstable step. Global clipping rescales all parameter gradients together, preserving their combined direction.';
 if(t.id==='target.ids')why='During training, the decoder must predict each target from earlier targets. Shifting the target right inserts <bos> and keeps the current answer out of that position’s input.';
 let result=t.op==='backward'||t.op==='gradient'?`The ${t.shape.join(' × ')} result contains loss sensitivities, not activations. A positive derivative means increasing that coordinate locally raises the loss. Shared paths contribute additively; a zero derivative means no first-order influence in this run.`:t.op==='mask'?'The tensor keeps its shape, but forbidden entries become −∞. Exponentiation later turns them into zero, so they contribute no value information. Turning the mask off in Experiment shows why the distinction matters.':t.op==='lookup'?'The output has one row per token and one column per learned feature. The same token begins with the same embedding; subsequent attention layers can give its occurrences different contextual representations.':t.id.endsWith('.A')?'Each row sums to one and belongs to one query position. These are probabilities computed from the current parameters. Their weighted value mixture is the next step; a high weight does not itself guarantee a correct prediction.':`This operation produces a ${t.shape.join(' × ')} tensor. Rows track positions and columns track this stage’s features (or keys/vocabulary items where indicated). Select a coordinate below to follow its exact operands; editing an upstream learned value recomputes this result and every dependent stage.`;
 if(t.op==='tokens')result='The integer IDs identify vocabulary entries. They are not quantities to compare: the learned embedding lookup, not arithmetic on the IDs, supplies the features used by the network.';
 if(t.op==='mean')result='The output is one scalar loss for the whole example. Its reverse derivative starts at 1, because changing the loss changes itself one-for-one. Backpropagation distributes that signal through the preceding operations.';
 if(t.op==='gather'||t.op==='neglog')result='There is one supervised target per decoder position. These selected probabilities or losses feed the average loss; they are used for learning, not supplied as inputs to the decoder at the same position.';
 if(t.id.startsWith('learn.'))result='These are parameter-update quantities, not token representations. The preview does not change the weights. Train one step applies the update to all active learned parameters and recomputes the entire model.';
 if(t.id==='target.ids')how=m.generation?`The current generated prefix is ${m.targetTokens.join(', ')}. It begins with <bos> and then contains the model’s own chosen tokens. No future target tokens are supplied; the last position predicts the next token.`:`During teacher forcing, the input is <bos> followed by all but the last target token. Here, ${m.targetTokens.join(', ')} predict ${m.targets.join(', ')}. A causal mask restricts each position to itself and earlier positions.`;
 if(/^((enc|dec)\.1)\.ff\.norm\.output$/.test(t.id)){why='The N× frame repeats the whole block. A second block can reinterpret the features built by the first; it has its own parameters rather than reusing the first block’s weights.';how='The same sequence of attention, residual addition, normalization and feed-forward operations runs again on the previous block’s output. Decoder blocks also include their own cross-attention to final encoder memory. This is the final normalized output of block 2.';}
 const paper=t.scope?.startsWith('enc')||t.scope?.startsWith('dec')?'§3 · Model architecture':t.scope==='training'?'§5 · Learning':t.scope==='source'||t.scope==='target'?'§3.4–3.5 · Input representations':'§3.4 · Prediction';
 return{why,how:how.replaceAll('cube','coordinate').replaceAll('They occupy independent depth layers in this scene.','The concatenation preserves both heads before the output projection.'),result,paper};
}
