import {liveSpatialState} from './live-space.js?v=b55dd29';
import {derivation} from './math.js?v=b55dd29';
import {calculate} from './course.js?v=b55dd29';
import {add,sub,mul,mix,normalize,cross,length,clamp,multiply,lookAt,perspective,modelMatrix,projectPoint} from './space.js?v=b55dd29';
// These are modeled points, vectors and linear maps, never a texture or traced outline.
export const vectorPages=new Set([3,4,5,6,8,14,26,27,28,32]);
const C={blue:[.29,.72,.96],teal:[.34,.94,.79],gold:[1,.78,.28],red:[1,.40,.35],purple:[.70,.51,.98],muted:[.19,.29,.34]};
const palette=[C.blue,C.teal,C.gold,C.purple];
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rounded=v=>'['+v.map(n=>n.toFixed(2)).join(', ')+']';
export function vectorState(model,scene,progress=.5,row=0){
 const p=clamp(progress),n=scene.reference,vectors=[],labels=[],points=[],segments=[],origin=[0,0,0];let title=scene.title,equation='',note='Three displayed coordinates from a four-dimensional toy embedding.',stage='',detail=null;
 const arrow=(name,to,color=C.blue,from=origin,ghost=false)=>{vectors.push({name,from:[...from],to:[...to],color,ghost});labels.push({text:name,pos:add(to,[0,.14,0]),color});};
 const dot=(name,pos,color=C.gold)=>points.push({name,pos,color});
 const E=model.tensors.get('source.lookup').values;
 if(n===4||n===5){
  const man=[1.5,1.05,.4],woman=[.6,1.6,.7],base=n===4?[-.8,1.7,-.5]:[-1.1,1.1,-.9],delta=sub(woman,man),target=add(base,delta),shown=add(base,mul(delta,p));
  const a=n===4?'uncle':'son',b=n===4?'aunt':'daughter';
  arrow('E(man)',man,C.blue);arrow('E(woman)',woman,C.red);arrow('E('+a+')',base,C.blue);arrow('E('+b+')',shown,C.red);arrow('shared offset',woman,C.gold,man);arrow('translate the offset',shown,C.gold,base);dot('moving endpoint',shown);
  equation=`E(${b}) = E(${a}) + t × (E(woman) − E(man))`;stage=`t = ${p.toFixed(2)} · offset ${rounded(delta)} · endpoint ${rounded(shown)}`;note='Illustrative coordinates constructed to demonstrate vector arithmetic; real embeddings only approximately exhibit such analogies.';
 }else if(n===6){
  const base=[.15,.75,.35],updates=[[-1,.65,.25],[1.05,.3,-.2],[-.25,.55,-.9]],names=['Shakespearean language','murdered predecessor','lived in Scotland'];let current=[...base];arrow('King · initial',base,C.blue,origin,true);
  const scaled=p*3;updates.forEach((delta,i)=>{const f=clamp(scaled-i),next=add(current,mul(delta,f));arrow(names[i],next,palette[i],current);current=next;});arrow('King · contextual',current,C.teal);dot('updated meaning',current,C.teal);equation='contextual vector = initial vector + successive context updates';stage='Current vector '+rounded(current);note='Conceptual context updates with explicit illustrative coordinates, not activations learned by the browser model.';
 }else if(n===8){
  const initial=[.7,.8,-.5],updates=[[-1,.6,.2],[.6,.8,.4],[.1,-.4,1.3]],names=['animal','quantity','skin'];arrow('E(mole) · shared',initial,C.gold,origin,true);updates.forEach((u,i)=>{const end=add(initial,mul(u,p));arrow(names[i],end,palette[i]);segments.push({a:initial,b:end,color:palette[i]});dot(names[i],end,palette[i]);});equation='same initial embedding + different context updates';stage='Context update strength t = '+p.toFixed(2);note='An illustrative construction: the shared starting coordinate is identical in all three contexts.';
 }else if([14,26,27,28,32].includes(n)){
  const role=n===14?'Q':'V',prefix=n===28?'enc.0.self.h1.':'enc.0.self.h0.',input=model.tensors.get('source.input'),weights=model.tensors.get('@'+prefix+'W'+role),output=model.tensors.get(prefix+role),r=Math.min(row,input.shape[0]-1),x=input.values[r],left=[-1.6,.8,0],right=[1.6,.8,0];
  // Input and output occupy independent coordinate frames; the 4D arithmetic stays intact.
  arrow('x · first 3 of 4',add(left,mul(x.slice(0,3),.8)),C.blue,left);const q=output.values[r],shown=[0,0,0];
  for(let k=0;k<4;k++){const amount=clamp(p*4-k),term=[x[k]*weights.values[k][0],x[k]*weights.values[k][1],0],next=add(shown,mul(term,amount));arrow('feature '+k,add(right,mul(next,1.1)),palette[k],add(right,mul(shown,1.1)));shown.splice(0,3,...next);}
  arrow(role+' · accumulated',add(right,mul(shown,1.1)),C.gold,right);dot('sum',add(right,mul(shown,1.1)));labels.push({text:'INPUT SPACE',pos:add(left,[0,-.35,0]),color:C.blue},{text:role+' SPACE',pos:add(right,[0,-.35,0]),color:C.gold});
  const k=Math.min(3,Math.floor(p*4)),contribution=weights.values[k].map(v=>x[k]*v);detail={title:`Feature ${k} creates one direction in ${role} space`,how:`x[${r},${k}] = ${x[k].toFixed(4)} multiplies W_${role}[${k}] = ${rounded(weights.values[k])}. Its full contribution is ${rounded(contribution)}. Add the four arrows head-to-tail to obtain ${rounded(q)}.`,why:`Each row of W_${role} specifies where one input feature points in the output space. The input value scales that direction. Training changes these learned directions; the projection is not a camera rotation.`};for(const frame of [left,right])for(let axis=0;axis<3;axis++){const end=[...frame];end[axis]+=1.15;segments.push({a:frame,b:end,color:[C.red,C.teal,C.blue][axis]});}equation=`${role}[${r}] = Σ x[${r}, k] × W_${role}[k]`;stage='Accumulate four feature contributions → '+rounded(q);note='Two output coordinates lie in a plane inside 3D. The left view shows only three of four input coordinates; all four contribute to the real multiplication.';
 }else{
  E.forEach((v,i)=>{const to=mul(v.slice(0,3),1.9),shown=to.map((value,axis)=>value*clamp(p*3-axis));arrow(model.sourceTokens[i],shown,palette[i%4]);dot(model.sourceTokens[i],shown,palette[i%4]);const foot=[shown[0],0,shown[2]];segments.push({a:shown,b:foot,color:palette[i%4]});});equation='token → E[token] → coordinates (x₀, x₁, x₂)';stage='Build coordinate '+Math.min(2,Math.floor(p*3))+' · completion '+Math.round(p*100)+'%';const selected=E[Math.min(row,E.length-1)],axis=Math.min(2,Math.floor(p*3));detail={title:`Place coordinate x${axis} on its basis direction`,how:`The selected token’s embedding is ${rounded(selected)}. Move ${selected[axis].toFixed(4)} units along basis direction ${axis}. Three displayed steps form its 3D endpoint; the fourth feature still participates in the model.`,why:'A token ID selects a learned row from the embedding table. Coordinates start as parameters and receive loss gradients during training. Individual dimensions do not have predefined human meanings.'};note='Real learned embedding coordinates from the current run. Coordinate 4 remains visible in All values; this 3D view is a slice, not the full embedding.';
 }

 // Resolve one vector into orthogonal coordinate displacements, with geometric projection guides.
 const selected=vectors.find(v=>v.name.includes('accumulated'))||vectors.filter(v=>!v.ghost)[Math.min(row,vectors.filter(v=>!v.ghost).length-1)];
 if(selected){let corner=[...selected.from];const delta=sub(selected.to,selected.from);for(let axis=0;axis<3;axis++){const next=[...corner];next[axis]+=delta[axis];segments.push({a:corner,b:next,color:[C.red,C.teal,C.blue][axis],component:true});points.push({name:'basis '+axis,pos:next,color:[C.red,C.teal,C.blue][axis]});corner=next;}const foot=[selected.to[0],selected.from[1],selected.to[2]];segments.push({a:selected.to,b:foot,color:C.muted},{a:foot,b:selected.from,color:C.muted});}
 if(!detail)detail={title:'Build a vector by adding displacements',how:stage+'. '+equation+'.',why:note+' Head-to-tail addition preserves each displacement. Coordinate guide lines resolve the displayed endpoint along independent axes.'};
 return {title,equation,stage,note,detail,vectors,points,segments,labels,progress:p};
}
export const vertexShader=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uVP;uniform mat4 uModel;uniform vec3 uColor;uniform float uAlpha;varying vec4 vColor;void main(){vec3 normal=normalize(mat3(uModel)*aNormal);float light=.62+.38*abs(dot(normal,normalize(vec3(.4,.8,1.))));vColor=vec4(uColor*light,uAlpha);gl_Position=uVP*uModel*vec4(aPosition,1.);}`;
export const fragmentShader=`precision mediump float;varying vec4 vColor;void main(){gl_FragColor=vColor;}`;
export function cylinderGeometry(cone=false,segments=18){const out=[];const push=(p,n)=>out.push(...p,...n);for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,b=(i+1)/segments*Math.PI*2,pa=[Math.cos(a),Math.sin(a),0],pb=[Math.cos(b),Math.sin(b),0],qa=cone?[0,0,1]:[...pa.slice(0,2),1],qb=cone?[0,0,1]:[...pb.slice(0,2),1],na=normalize([pa[0],pa[1],cone?1:0]),nb=normalize([pb[0],pb[1],cone?1:0]);push(pa,na);push(pb,nb);push(qa,na);if(!cone){push(pb,nb);push(qb,nb);push(qa,na);}push([0,0,0],[0,0,-1]);push(pb,[0,0,-1]);push(pa,[0,0,-1]);}return new Float32Array(out);}
export function sphereGeometry(){const out=[];const pt=(a,b)=>[Math.cos(a)*Math.sin(b),Math.cos(b),Math.sin(a)*Math.sin(b)];for(let i=0;i<16;i++)for(let j=0;j<8;j++){const a=i/16*Math.PI*2,b=(i+1)/16*Math.PI*2,c=j/8*Math.PI,d=(j+1)/8*Math.PI;for(const p of [pt(a,c),pt(b,c),pt(a,d),pt(b,c),pt(b,d),pt(a,d)])out.push(...p,...p);}return new Float32Array(out);}
export function cameraMatrix(yaw=-.45,pitch=.43,aspect=1.5,zoom=1){const distance=7.8/zoom,eye=[Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance];return multiply(perspective(Math.PI/4,aspect,.05,60),lookAt(eye,[0,.6,0]));}
export function sceneMeshes(state){const meshes=[];const rod=(a,b,color,width=.012,alpha=1)=>{const d=sub(b,a),len=length(d);if(len<.00001)return;meshes.push({kind:'cylinder',matrix:modelMatrix(a,[width,width,len],d),color,alpha});};
 for(let i=-6;i<=6;i++){rod([i*.5,0,-3],[i*.5,0,3],C.muted,.004,.55);rod([-3,0,i*.5],[3,0,i*.5],C.muted,.004,.55);}
 for(const [to,col] of [[[2.8,0,0],C.red],[[0,2.8,0],C.teal],[[0,0,2.8],C.blue]])rod([0,0,0],to,col,.009,.8);
 for(const s of state.segments)rod(s.a,s.b,s.color,s.component?.014:.004,s.component?.8:.45);
 for(const v of state.vectors){const d=sub(v.to,v.from),len=length(d);if(len<.01)continue;const head=Math.min(.17,len*.28),base=sub(v.to,mul(normalize(d),head));rod(v.from,base,v.color,v.ghost?.008:.017,v.ghost?.25:1);meshes.push({kind:'cone',matrix:modelMatrix(base,[head*.38,head*.38,head],d),color:v.color,alpha:v.ghost?.25:1});}
 for(const p of state.points){meshes.push({kind:'sphere',matrix:modelMatrix(p.pos,[p.radius||.038,p.radius||.038,p.radius||.038]),color:p.color,alpha:1});for(const r of [.065,.095,.125])meshes.push({kind:'sphere',matrix:modelMatrix(p.pos,[r,r,r]),color:p.color,alpha:.06});}return meshes;
}
export class VectorSpace{
 constructor(host){this.host=document.createElement('div');this.host.className='vector-space';host.append(this.host);this.host.innerHTML='<div class="vector-heading"><span>3D VECTOR SPACE</span><h2></h2></div><canvas aria-label="Interactive three-dimensional vectors and coordinate axes" tabindex="0"></canvas><div class="vector-labels"></div><div class="vector-matrix" hidden></div><div class="vector-readout"><strong></strong><output></output><p></p></div><div class="vector-camera"><span>Drag to inspect · scroll to learn</span><div class="perspective-buttons"><button type="button">Reset</button><button type="button" data-perspective="front">Front</button><button type="button" data-perspective="top">Top</button><button type="button" data-perspective="space">Perspective</button></div></div>';this.canvas=this.host.querySelector('canvas');this.labels=this.host.querySelector('.vector-labels');this.yaw=-.45;this.pitch=.43;this.zoom=1;this.gl=this.canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:false});this.host.querySelector('button').onclick=()=>this.reset();this.host.querySelectorAll('[data-perspective]').forEach(b=>b.onclick=()=>{const angles={front:[0,.08],top:[0,1.48],space:[-.65,.5]}[b.dataset.perspective];this.yaw=angles[0];this.pitch=angles[1];this.render();});
 this.canvas.addEventListener('pointerdown',ev=>{if(ev.pointerType==='touch')return;this.drag={x:ev.clientX,y:ev.clientY};this.canvas.setPointerCapture(ev.pointerId);});this.canvas.addEventListener('pointermove',ev=>{if(!this.drag)return;this.yaw-=(ev.clientX-this.drag.x)*.006;this.pitch=clamp(this.pitch+(ev.clientY-this.drag.y)*.006,-.15,1.1);this.drag={x:ev.clientX,y:ev.clientY};this.render();});this.canvas.addEventListener('pointerup',()=>this.drag=null);this.canvas.addEventListener('pointercancel',()=>this.drag=null);this.canvas.addEventListener('keydown',ev=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();ev.stopPropagation();this.yaw+=(ev.key==='ArrowLeft'?.08:ev.key==='ArrowRight'?-.08:0);this.pitch=clamp(this.pitch+(ev.key==='ArrowUp'?.08:ev.key==='ArrowDown'?-.08:0),-.15,1.1);this.render();}});
 this.canvas.addEventListener('webglcontextlost',ev=>{ev.preventDefault();this.lost=true;});this.canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.init();this.render();});if(this.gl)this.init();else{this.host.classList.add('no-webgl');this.host.querySelector('.vector-camera span').textContent='3D unavailable on this device · projected geometry shown';}
 }
 init(){const gl=this.gl,shader=(type,code)=>{const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};this.program=gl.createProgram();gl.attachShader(this.program,shader(gl.VERTEX_SHADER,vertexShader));gl.attachShader(this.program,shader(gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));this.u=Object.fromEntries(['VP','Model','Color','Alpha'].map(s=>[s,gl.getUniformLocation(this.program,'u'+s)]));this.pos=gl.getAttribLocation(this.program,'aPosition');this.normal=gl.getAttribLocation(this.program,'aNormal');this.buffers={};for(const [name,data] of [['cylinder',cylinderGeometry()],['cone',cylinderGeometry(true)],['sphere',sphereGeometry()]]){const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);this.buffers[name]={buffer,count:data.length/6};}gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,1);}
 reset(){this.yaw=-.45;this.pitch=.43;this.render();}
 set(model,scene,phase,row=0,col=0){if(this.scene?.id!==scene.id){const network=/\.ff\.(expand|biased|relu|contract|bias)$/.test(scene.tensor),bars=/\.(A|scores|masked|exp|sum)$/.test(scene.tensor);this.yaw=network?-.7:bars?-.22:-.45;this.pitch=network?.28:bars?.18:.43;}this.model=model;this.scene=scene;this.row=row;this.col=col;this.state=vectorPages.has(scene.reference)?vectorState(model,scene,phase,row):liveSpatialState(model,scene,phase,row,col);const panel=this.host.querySelector('.vector-matrix'),projection=[14,26,27,28,32].includes(scene.reference);panel.hidden=!projection;if(projection){const role=scene.reference===14?'Q':'V',head=scene.reference===28?1:0,key='@enc.0.self.h'+head+'.W'+role,t=model.tensors.get(key),signature=key+JSON.stringify(t.values);if(signature!==this.matrixSignature){panel.innerHTML='<p>W<sub>'+role+'</sub> · learned projection</p><table>'+t.values.map((r,i)=>'<tr>'+r.map((v,j)=>'<td><button data-tensor="'+key+'" data-row="'+i+'" data-col="'+j+'">'+v.toFixed(3)+'</button></td>').join('')+'</tr>').join('')+'</table><small>4 input features → 2 outputs</small>';this.matrixSignature=signature;}}const ruleId=[14,26,27,28,32].includes(scene.reference)?'enc.0.self.h'+(scene.reference===28?1:0)+'.'+(scene.reference===14?'Q':'V'):scene.tensor;const t=model.tensors.get(ruleId);if(t&&!scene.visualOnly){const key=t.id+':'+row+':'+col;if(key!==this.ruleKey){const html=derivation(model,calculate(model,t.id,row,col)),match=html.match(/<math[\s\S]*?<\/math>/);this.spatialRule=match?.[0]||'';this.ruleKey=key;}}else{this.spatialRule='';this.ruleKey='';}this.render();}
 render(){if(!this.state||this.host.hidden)return;const rect=this.canvas.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height),dpr=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==Math.round(w*dpr)||this.canvas.height!==Math.round(h*dpr)){this.canvas.width=Math.round(w*dpr);this.canvas.height=Math.round(h*dpr);}const extent=Math.max(3,...this.state.vectors.flatMap(v=>v.from.concat(v.to).map(Math.abs)));const vp=cameraMatrix(this.yaw,this.pitch,w/h,this.zoom*3/extent);const gl=this.gl;
  if(gl&&!this.lost){gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);gl.uniformMatrix4fv(this.u.VP,false,vp);for(const obj of sceneMeshes(this.state)){const b=this.buffers[obj.kind];gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.enableVertexAttribArray(this.pos);gl.vertexAttribPointer(this.pos,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(this.normal);gl.vertexAttribPointer(this.normal,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(this.u.Model,false,obj.matrix);gl.uniform3fv(this.u.Color,obj.color);gl.uniform1f(this.u.Alpha,obj.alpha);gl.drawArrays(gl.TRIANGLES,0,b.count);}}
  const at=p=>projectPoint(vp,p,w,h);const labels=[...this.state.labels,{text:'x₀',pos:[2.95,0,0],color:C.red},{text:'x₁',pos:[0,2.95,0],color:C.teal},{text:'x₂',pos:[0,0,2.95],color:C.blue}];const used=[];this.labels.innerHTML=labels.map(l=>{const p=at(l.pos);p.x=clamp(p.x,70,w-70);p.y=clamp(p.y,12,h-24);let guard=0;while(used.some(q=>Math.abs(q.x-p.x)<110&&Math.abs(q.y-p.y)<24)&&guard++<8)p.y+=25;used.push(p);return p.w>0?`<span style="left:${p.x}px;top:${p.y}px;color:rgb(${l.color.map(v=>Math.round(v*255)).join(',')})">${e(l.text)}</span>`:'';}).join('');
  if(!gl){const rgb=c=>'rgb('+c.map(x=>Math.round(x*255)).join(',')+')',line=(a,b,c,width=1,opacity=.6)=>{a=at(a);b=at(b);return `<path d="M${a.x} ${a.y}L${b.x} ${b.y}" fill="none" stroke="${rgb(c)}" stroke-width="${width}" opacity="${opacity}"/>`;};let geometry='';for(let k=-3;k<=3;k+=.5){geometry+=line([k,0,-3],[k,0,3],[.12,.3,.27],.6,.4)+line([-3,0,k],[3,0,k],[.12,.3,.27],.6,.4);}for(let axis=0;axis<3;axis++){const end=[0,0,0];end[axis]=3;geometry+=line([0,0,0],end,[C.red,C.teal,C.blue][axis],1.5,.8);}for(const s of this.state.segments)geometry+=line(s.a,s.b,s.color,s.component?2:1,s.component?.9:.4);for(const v of this.state.vectors){geometry+=line(v.from,v.to,v.color,3,v.ghost?.3:1);const a=at(v.from),b=at(v.to),angle=Math.atan2(b.y-a.y,b.x-a.x);geometry+=`<path d="M${b.x-9*Math.cos(angle-.4)} ${b.y-9*Math.sin(angle-.4)}L${b.x} ${b.y}L${b.x-9*Math.cos(angle+.4)} ${b.y-9*Math.sin(angle+.4)}" fill="none" stroke="${rgb(v.color)}" stroke-width="2"/>`;}for(const point of this.state.points){const p=at(point.pos),r=Math.max(3,(point.radius||.038)*35);geometry+=`<circle cx="${p.x}" cy="${p.y}" r="${r+5}" fill="${rgb(point.color)}" opacity=".12"/><circle cx="${p.x}" cy="${p.y}" r="${r}" fill="${rgb(point.color)}"/>`;}this.labels.insertAdjacentHTML('afterbegin',`<svg viewBox="0 0 ${w} ${h}" aria-hidden="true">${geometry}</svg>`);}

  this.host.querySelector('h2').textContent=this.state.title;if(this.spatialRule)this.host.querySelector('strong').innerHTML=this.spatialRule;else this.host.querySelector('strong').textContent=this.state.equation;this.host.querySelector('output').textContent=this.state.stage;this.host.querySelector('.vector-readout p').textContent=this.state.note;
 }
}
